# Railway service configuration
$schema: https://railway.app/railway.schema.json
version: 2

deploy:
  startCommand: npm start
  restartPolicyType: on_failure
  restartPolicyMaxRetries: 10

variables:
  NODE_ENV: production
  PORT: ${{ PORT }}

healthcheck:
  httpPath: /api/health
  httpTimeout: 10
  httpInterval: 30
