name: Deploy Backend to Azure Container App

on:
  push:
    branches:
      - main
    paths:
      - 'backend/**'
      - '.github/workflows/azure-container-app-backend.yml'
  pull_request:
    branches:
      - main
    paths:
      - 'backend/**'
      - '.github/workflows/azure-container-app-backend.yml'
  workflow_dispatch:

env:
  AZURE_CONTAINER_REGISTRY: cerregistry2025
  CONTAINER_NAME: cer-backend
  RESOURCE_GROUP: rg-cer-prod
  IMAGE_NAME: cer-backend

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Log in to Azure Container Registry
      run: az acr login --name ${{ env.AZURE_CONTAINER_REGISTRY }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: ./backend
        push: true
        tags: |
          ${{ env.AZURE_CONTAINER_REGISTRY }}.azurecr.io/${{ env.IMAGE_NAME }}:latest
          ${{ env.AZURE_CONTAINER_REGISTRY }}.azurecr.io/${{ env.IMAGE_NAME }}:${{ github.sha }}
        platforms: linux/amd64
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: Run Database Migrations
      uses: azure/CLI@v1
      with:
        inlineScript: |
          # Run migrations in a temporary container
          az containerapp job create \
            --name migration-job-${{ github.sha }} \
            --resource-group ${{ env.RESOURCE_GROUP }} \
            --environment-variables \
              DB_HOST="${{ secrets.DB_HOST }}" \
              DB_PORT="${{ secrets.DB_PORT }}" \
              DB_NAME="${{ secrets.DB_NAME }}" \
              DB_USER="${{ secrets.DB_USER }}" \
              DB_PASSWORD="${{ secrets.DB_PASSWORD }}" \
            --image ${{ env.AZURE_CONTAINER_REGISTRY }}.azurecr.io/${{ env.IMAGE_NAME }}:${{ github.sha }} \
            --command "npm run db:migrate" \
            --replica-timeout 300 \
            --parallelism 1 \
            --replica-completion-count 1 || true
          
          # Start the migration job
          az containerapp job start \
            --name migration-job-${{ github.sha }} \
            --resource-group ${{ env.RESOURCE_GROUP }}
          
          # Clean up migration job
          sleep 60
          az containerapp job delete \
            --name migration-job-${{ github.sha }} \
            --resource-group ${{ env.RESOURCE_GROUP }} \
            --yes

    - name: Deploy to Azure Container App
      uses: azure/CLI@v1
      with:
        inlineScript: |
          az containerapp update \
            --name ${{ env.CONTAINER_NAME }} \
            --resource-group ${{ env.RESOURCE_GROUP }} \
            --image ${{ env.AZURE_CONTAINER_REGISTRY }}.azurecr.io/${{ env.IMAGE_NAME }}:${{ github.sha }} \
            --min-replicas 0 \
            --max-replicas 2 \
            --cpu 0.25 \
            --memory 0.5Gi

    - name: Logout from Azure
      run: az logout
